In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
#显示所有行
pd.set_option('display.max_rows', None)
#设置value的显示长度为100，默认为50
pd.set_option('max_colwidth',100)

In [28]:
admet_data=pd.read_excel("../化合物ADMET.xlsx")

In [29]:
admet_data['MN'].unique()

array([0, 1], dtype=int64)

In [30]:
def handleLabel_mn(dataframe):
    global anomaly_list
    #print(dataframe['MN'])
    if dataframe['MN']  != 1:
        return 'good'
    else:
        return 'bad'
    
def handleLabel_her(dataframe):
    global anomaly_list
    #global label_list  #在函数内部使用全局变量并修改它
    if dataframe['hERG']  != 1:
        return 'good'
    else:
        return 'bad'

In [31]:
admet_data['MN']=admet_data.apply(lambda r:handleLabel_mn(r),axis=1)#每一行来传
admet_data['hERG']=admet_data.apply(lambda r:handleLabel_her(r),axis=1)

In [32]:
admet_data['MN'].unique()

array(['good', 'bad'], dtype=object)

In [33]:
admet_data['hERG'].unique()

array(['bad', 'good'], dtype=object)

In [34]:
def handleLabel_imn(dataframe):
    global anomaly_list
    #print(dataframe['MN'])
    if dataframe['MN']  == 'good':
        return 1
    else:
        return 0
    
def handleLabel_iher(dataframe):
    #global label_list  #在函数内部使用全局变量并修改它
    if dataframe['hERG']  == 'good':
        return 1
    else:
        return 0

In [35]:
admet_data['MN']=admet_data.apply(lambda r:handleLabel_imn(r),axis=1)#每一行来传
admet_data['hERG']=admet_data.apply(lambda r:handleLabel_iher(r),axis=1)

In [37]:
def count_good_label(dataframe):
    #global label_list  #在函数内部使用全局变量并修改它
    if dataframe[1]+dataframe[2]+dataframe[3]+dataframe[4]+dataframe[5] >= 3:
        return 1
    else:
        return 0

In [39]:
admet_data['own_3_good'] = admet_data.apply(lambda r:count_good_label(r),axis=1)

In [70]:
admet_data['own_3_good'].value_counts()

0    1342
1     632
Name: own_3_good, dtype: int64

In [41]:
admet_data.to_csv('admet_q4.csv',index=False)

In [45]:
era_df = pd.read_pickle('../pickle/ult_20_dummy.pkl')
era_df.head()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM
0,32.50,0.01887,4,1.04839,11,-0.080148,0.0,0.460175,0,912,0.0,-0.217040,0.00500,0.0,0,4128.339568,2.5
1,33.50,0.01772,4,1.01515,11,-0.080148,0.0,0.460175,0,976,0.0,-0.217040,0.00469,0.0,0,4811.560374,7.5
2,40.25,0.02094,5,1.21970,16,-0.059065,0.0,0.519350,0,977,0.0,-0.236031,0.00791,0.0,0,4479.177597,3.1
3,33.50,0.01823,4,1.01515,11,-0.079743,0.0,0.460206,0,983,0.0,-0.216970,0.00520,0.0,0,4311.294610,3.9
4,39.50,0.01823,4,1.19697,16,-0.069664,0.0,0.462912,0,983,0.0,-0.215099,0.00520,0.0,0,4265.064807,7.4

In [48]:
df1 = pd.concat([era_df,admet_data['own_3_good']],axis=1)
df1.head()
df1.to_pickle('Q4/q4.pkl')

In [51]:
np.set_printoptions(suppress=True) 
df1['IC50_nM'].describe()
# min 0.046   25% 是27

count    1.974000e+03
mean     9.910490e+03
std      1.055204e+05
min      4.600000e-02
25%      2.702500e+01
50%      2.625000e+02
75%      4.148125e+03
max      3.500000e+06
Name: IC50_nM, dtype: float64

In [68]:
df1['own_3_good'].describe()

count    1974.000000
mean        0.320162
std         0.466657
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: own_3_good, dtype: float64

In [71]:
high_27_era = df1[df1['IC50_nM']<27]
high_27_era.describe()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM,own_3_good
count,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.000000,487.00000
mean,41.173511,0.024467,4.811088,1.262197,14.854209,-0.019275,0.167916,0.485568,0.365503,944.924025,0.099836,-0.226977,0.012364,0.167916,0.338809,4541.749059,6.611737,0.13963
std,6.964429,0.005093,1.719305,0.120520,3.097407,0.109251,0.944922,0.181853,0.840023,361.939808,0.641790,0.104329,0.005661,0.944922,0.919716,916.953709,6.987483,0.34696
min,18.500000,0.010420,1.000000,0.780490,0.000000,-1.242501,0.000000,0.056241,0.000000,293.000000,-1.428271,-0.964036,0.001060,0.000000,0.000000,1694.137014,0.046000,0.00000
25%,38.625000,0.020940,4.000000,1.199265,14.000000,-0.074853,0.000000,0.393588,0.000000,798.000000,0.000000,-0.258396,0.008185,0.000000,0.000000,4191.433334,1.105000,0.00000
50%,41.500000,0.023850,5.000000,1.235290,15.000000,-0.036974,0.000000,0.496935,0.000000,976.000000,0.000000,-0.230330,0.010920,0.000000,0.000000,4564.651431,4.000000,0.00000
75%,44.500000,0.027455,5.000000,1.326945,16.000000,0.021020,0.000000,0.570212,1.000000,1062.000000,0.050978,-0.182856,0.015120,0.000000,0.000000,4939.317497,10.000000,0.00000
max,65.750000,0.041790,27.000000,1.600000,23.000000,0.339239,5.871480,2.053664,10.000000,3429.000000,1.402910,-0.017044,0.033390,5.871480,3.000000,9076.235009,26.000000,1.00000

In [73]:
all_high = high_27_era[high_27_era['own_3_good']==1]
all_high.describe()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM,own_3_good
count,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.0
mean,36.341912,0.026956,4.058824,1.293882,13.000000,-0.010457,0.241305,0.397115,0.367647,700.529412,0.119272,-0.190512,0.015049,0.241305,0.529412,3992.613437,10.757397,1.0
std,9.827894,0.006002,1.794539,0.154025,4.246157,0.076895,1.133168,0.226677,0.620650,431.234274,0.679096,0.148521,0.006768,1.133168,1.125957,1143.506982,8.147972,0.0
min,18.500000,0.014790,1.000000,0.916670,4.000000,-0.174236,0.000000,0.061486,0.000000,304.000000,-1.212900,-0.699920,0.001060,0.000000,0.000000,1904.701340,0.138000,1.0
25%,29.187500,0.022730,3.000000,1.216797,11.000000,-0.063675,0.000000,0.242702,0.000000,364.000000,-0.038526,-0.260213,0.009900,0.000000,0.000000,3282.557452,3.435000,1.0
50%,33.875000,0.027220,4.000000,1.297920,12.500000,0.000697,0.000000,0.346332,0.000000,579.500000,0.000000,-0.179368,0.014540,0.000000,0.000000,3945.138208,8.885000,1.0
75%,42.000000,0.031672,5.000000,1.418750,15.000000,0.019154,0.000000,0.551564,1.000000,894.000000,0.069499,-0.054120,0.019545,0.000000,0.000000,4815.058904,18.000000,1.0
max,60.750000,0.038490,9.000000,1.583330,22.000000,0.283202,5.871480,1.042658,2.000000,2598.000000,1.374907,-0.017044,0.027350,5.871480,3.000000,6248.087741,26.000000,1.0

In [74]:
all_high0 = high_27_era[high_27_era['own_3_good']==0]
all_high0.describe()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM,own_3_good
count,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.000000,419.0
mean,41.957637,0.024063,4.933174,1.257055,15.155131,-0.020706,0.156006,0.499923,0.365155,984.587112,0.096682,-0.232895,0.011929,0.156006,0.307876,4630.868921,5.938933,0.0
std,6.041362,0.004817,1.677410,0.113559,2.759462,0.113644,0.911752,0.169514,0.871027,333.482342,0.636326,0.094171,0.005344,0.911752,0.879435,843.193696,6.548032,0.0
min,25.500000,0.010420,1.000000,0.780490,0.000000,-1.242501,0.000000,0.056241,0.000000,293.000000,-1.428271,-0.964036,0.003980,0.000000,0.000000,1694.137014,0.046000,0.0
25%,39.875000,0.020940,4.000000,1.198530,15.000000,-0.075741,0.000000,0.420690,0.000000,841.500000,0.000000,-0.257852,0.008160,0.000000,0.000000,4307.458638,1.000000,0.0
50%,41.750000,0.023450,5.000000,1.228570,15.000000,-0.041666,0.000000,0.508359,0.000000,994.000000,0.000000,-0.232087,0.010560,0.000000,0.000000,4600.789463,3.300000,0.0
75%,44.625000,0.027000,5.000000,1.318245,16.000000,0.021915,0.000000,0.570332,0.500000,1076.000000,0.050978,-0.198932,0.014630,0.000000,0.000000,4958.798591,9.000000,0.0
max,65.750000,0.041790,27.000000,1.600000,23.000000,0.339239,5.859647,2.053664,10.000000,3429.000000,1.402910,-0.017852,0.033390,5.859647,3.000000,9076.235009,26.000000,0.0

In [61]:
high_6_era = df1[df1['IC50_nM']<1]
high_6_era.describe()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM,own_3_good
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000
mean,42.355769,0.025009,4.788462,1.238742,15.480769,-0.029121,0.056343,0.503660,0.153846,999.000000,0.235428,-0.230556,0.012408,0.056343,0.086538,4728.594152,0.494250,0.038462
std,4.803252,0.003579,0.820526,0.071131,2.401378,0.083853,0.574586,0.107083,0.412646,175.328928,0.628337,0.065853,0.004343,0.574586,0.443082,578.780391,0.239287,0.193239
min,25.500000,0.017890,2.000000,1.028570,9.000000,-0.127448,0.000000,0.112795,0.000000,340.000000,-1.230476,-0.699920,0.004450,0.000000,0.000000,2271.841755,0.046000,0.000000
25%,40.750000,0.022687,5.000000,1.198530,15.000000,-0.069761,0.000000,0.486257,0.000000,950.500000,0.000000,-0.238454,0.009675,0.000000,0.000000,4488.295744,0.300000,0.000000
50%,41.875000,0.024850,5.000000,1.221430,15.000000,-0.051699,0.000000,0.515663,0.000000,1008.500000,0.000000,-0.234034,0.012440,0.000000,0.000000,4685.836440,0.500000,0.000000
75%,42.875000,0.026550,5.000000,1.259832,16.000000,-0.014539,0.000000,0.528960,0.000000,1058.250000,0.962478,-0.219067,0.013775,0.000000,0.000000,4883.128045,0.700000,0.000000
max,58.000000,0.040460,8.000000,1.450000,23.000000,0.320744,5.859647,1.042658,2.000000,1446.000000,1.308985,-0.035433,0.031860,5.859647,3.000000,6182.157059,0.970000,1.000000

In [63]:
high_3_era = df1[df1['IC50_nM']<0.3]
high_3_era.describe()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM,own_3_good
count,23.000000,23.000000,23.000000,23.000000,23.00000,23.000000,23.0,23.000000,23.000000,23.000000,23.000000,23.000000,23.000000,23.0,23.000000,23.000000,23.000000,23.000000
mean,43.434783,0.026070,4.695652,1.248661,15.26087,-0.022260,0.0,0.499131,0.173913,1021.521739,0.454386,-0.231795,0.014079,0.0,0.043478,4923.762664,0.189304,0.043478
std,4.632652,0.004688,0.634950,0.087115,2.94213,0.089533,0.0,0.101162,0.387553,186.279328,0.771067,0.064472,0.005313,0.0,0.208514,534.777742,0.052927,0.208514
min,34.750000,0.021150,3.000000,1.028570,9.00000,-0.105734,0.0,0.253525,0.000000,602.000000,-1.230476,-0.490287,0.008930,0.0,0.000000,3633.932245,0.046000,0.000000
25%,42.500000,0.023075,4.000000,1.220090,15.00000,-0.102466,0.0,0.483528,0.000000,996.000000,0.005259,-0.239956,0.011845,0.0,0.000000,4742.617507,0.200000,0.000000
50%,42.750000,0.025260,5.000000,1.221430,15.00000,-0.016848,0.0,0.492640,0.000000,1028.000000,0.962448,-0.236081,0.012560,0.0,0.000000,4787.181901,0.200000,0.000000
75%,44.875000,0.027400,5.000000,1.319855,16.50000,0.021993,0.0,0.495403,0.000000,1064.000000,0.965380,-0.199356,0.015120,0.0,0.000000,5189.783626,0.200000,0.000000
max,56.000000,0.040460,6.000000,1.421050,23.00000,0.196462,0.0,0.876214,1.000000,1388.000000,1.308985,-0.124475,0.031860,0.0,1.000000,6034.706082,0.280000,1.000000

In [64]:
high_3_era = df1[df1['IC50_nM']<=0.046]
high_3_era.describe()

,ETA_Beta,ETA_EtaP_B_RC,nHBAcc_Lipinski,ETA_BetaP,C2SP2,ATSc5,maxaaO,ATSc1,C1SP2,ECCEN,mindssC,ATSc2,ETA_EtaP_B,minaaO,nTG12Ring,ATSp4,IC50_nM,own_3_good
count,1.0,1.00000,1.0,1.00000,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.00000,1.0,1.0,1.000000,1.000,1.0
mean,45.0,0.02246,4.0,1.32353,17.0,-0.016848,0.0,0.456551,0.0,1047.0,0.063355,-0.194168,0.00981,0.0,0.0,4830.278047,0.046,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,45.0,0.02246,4.0,1.32353,17.0,-0.016848,0.0,0.456551,0.0,1047.0,0.063355,-0.194168,0.00981,0.0,0.0,4830.278047,0.046,0.0
25%,45.0,0.02246,4.0,1.32353,17.0,-0.016848,0.0,0.456551,0.0,1047.0,0.063355,-0.194168,0.00981,0.0,0.0,4830.278047,0.046,0.0
50%,45.0,0.02246,4.0,1.32353,17.0,-0.016848,0.0,0.456551,0.0,1047.0,0.063355,-0.194168,0.00981,0.0,0.0,4830.278047,0.046,0.0
75%,45.0,0.02246,4.0,1.32353,17.0,-0.016848,0.0,0.456551,0.0,1047.0,0.063355,-0.194168,0.00981,0.0,0.0,4830.278047,0.046,0.0
max,45.0,0.02246,4.0,1.32353,17.0,-0.016848,0.0,0.456551,0.0,1047.0,0.063355,-0.194168,0.00981,0.0,0.0,4830.278047,0.046,0.0